calorie_counting: calorie_counting.cpp
	g++ -std=c++11 ./calorie_counting.cpp -o calorie_counting

run:
	./calorie_counting ./data/input.txt 1 
	./calorie_counting ./data/input.txt 3

clean:
	rm -f ./calorie_counting
