rock_paper_scissors_pt1: rock_paper_scissors_pt1.cpp
	g++ -std=c++11 ./rock_paper_scissors_pt1.cpp -o rock_paper_scissors_pt1 

rock_paper_scissors_pt2: rock_paper_scissors_pt2.cpp
	g++ -std=c++11 ./rock_paper_scissors_pt2.cpp -o rock_paper_scissors_pt2


run:
	./rock_paper_scissors_pt1 ./data/input.txt 
	./rock_paper_scissors_pt2 ./data/input.txt 

clean:
	rm -f ./rock_paper_scissors_pt1 ./rock_paper_scissors_pt2
